Adição de fluxo para upload de arquivos .json e .parquet nos buckets 'layer_raw' e 'layer_2' no Google Cloud Storage
sejabazico/etl pull request #3
Opened 2023-01-26 19:43 UTC by juliovinicius

2023-01-26 21:22 UTC, sejabazico requested changes

2023-01-26 21:22 UTC, sejabazico commented on carregadores/google_cloud_storage.py
> +def subir_para_o_bucket(caminho_do_arquivo, id_projeto, nome_do_bucket):
Faltou a anotação de tipos aqui na definição da função.

Pelo contexto, imagino que seja:
```python
def subir_para_o_bucket(caminho_do_arquivo: str, id_projeto: str, nome_do_bucket: str) -> IO:
```

2023-01-30 19:08 UTC, juliovinicius commented on carregadores/google_cloud_storage.py
> +def subir_para_o_bucket(caminho_do_arquivo, id_projeto, nome_do_bucket):
Adicionado

2023-01-30 19:15 UTC, sejabazico approved these changes

2023-01-30 19:15 UTC, merged